name: mshdtf-env
channels:
  - bioconda
  - conda-forge
  - dnachun
dependencies:
  - r-base
  - scanpy
  - scipy==1.10
  - python-igraph
  - leidenalg
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - 'bioconductor-annotationdbi >=1.64.0,<1.65.0'
  - 'bioconductor-biocfilecache >=2.10.0,<2.11.0'
  - r-base
  - r-digest
  - r-httr
  - r-progress
  - r-rappdirs
  - r-stringr
  - r-xml2
  - libxml2
  - r-biocmanager
