name: mshdtf-env
channels:
  - conda-forge
dependencies:
  - python >=3.10
  - scanpy
  - anndata==0.10
  - pandas>1.0.0
  - numpy>=1.19.0
  - matplotlib
  - seaborn
  - umap-learn>=0.4.6
  - requests
  - scipy>=1.3.1
  - scikit-learn>=0.23.1
  - numba>=0.50.1
  - packaging>=0.20.0
  - dill
  - ipython
  - h5py
  - hnswlib
  - python-igraph
  - leidenalg
  - pip:
    - sam-algorithm
   

